import type {
  Employee,
  VacationRequest,
  Notification,
  Document,
  Course,
  CourseEnrollment,
  HeadcountData,
  SkillDistribution,
  TurnoverData,
} from "./types"

export const mockEmployees: Employee[] = [
  {
    id: "1",
    fullName: "María García López",
    preferredName: "Mari",
    email: "maria.garcia@dacodes.com",
    phone: "+52 55 1234 5678",
    avatar: "/professional-woman-dark-hair.png",
    role: "Senior Backend Engineer",
    seniority: "Senior",
    service: "AI Technologies",
    squad: "Squad Aura",
    client: "Interprotección",
    project: "Aura Platform",
    status: "active",
    workload: "full-time",
    country: "México",
    countryCode: "MX",
    startDate: "2021-03-15",
    yearsOfExperience: 7,
    englishLevel: "C1",
    usClientExperience: true,
    skills: [
      { id: "1", name: "Python", yearsOfExperience: 5, level: "expert", verified: true },
      { id: "2", name: "Node.js", yearsOfExperience: 4, level: "advanced", verified: true },
      { id: "3", name: "AWS", yearsOfExperience: 3, level: "advanced", verified: true },
      { id: "4", name: "PostgreSQL", yearsOfExperience: 5, level: "expert", verified: false },
      { id: "5", name: "Docker", yearsOfExperience: 3, level: "advanced", verified: true },
      { id: "6", name: "Kubernetes", yearsOfExperience: 2, level: "intermediate", verified: false },
    ],
    certifications: [
      { id: "1", name: "AWS Solutions Architect", issuer: "Amazon", date: "2023-06-15" },
      { id: "2", name: "Python Professional", issuer: "Python Institute", date: "2022-03-20" },
    ],
    flags: [
      {
        id: "1",
        type: "blue",
        title: "Excelente trabajo en demo",
        description: "Presentación impecable ante el cliente, destacó por su conocimiento técnico",
        date: "2024-01-15",
        reportedBy: "Carlos Mendoza",
      },
    ],
    trainings: [
      {
        id: "1",
        name: "AI Fundamentals",
        category: "Technical",
        status: "completed",
        completedDate: "2024-01-20",
        progress: 100,
      },
      {
        id: "2",
        name: "Leadership 101",
        category: "Soft Skills",
        status: "in-progress",
        dueDate: "2024-03-01",
        progress: 60,
      },
    ],
    badges: [
      {
        id: "1",
        name: "AI Champion",
        icon: "🤖",
        description: "Completó certificación de IA",
        earnedDate: "2024-01-20",
      },
      {
        id: "2",
        name: "Team Player",
        icon: "🤝",
        description: "Reconocido por colaboración",
        earnedDate: "2023-11-15",
      },
    ],
    paymentInfo: {
      scheme: "nomina",
      channel: "BBVA",
      nextPaymentDate: "2024-02-15",
      lastPaymentDate: "2024-01-31",
      estimatedAmount: 45000,
      currency: "MXN",
    },
    vacationDays: 15,
    vacationDaysUsed: 5,
    manager: "Carlos Mendoza",
    bio: "Backend engineer apasionada por la arquitectura de sistemas y la IA. Me encanta resolver problemas complejos y mentorear a nuevos developers.",
  },
  {
    id: "2",
    fullName: "Carlos Mendoza Rivera",
    preferredName: "Carlos",
    email: "carlos.mendoza@dacodes.com",
    avatar: "/professional-bearded-man.png",
    role: "Tech Lead",
    seniority: "Lead",
    service: "Core Development",
    squad: "Squad Phoenix",
    client: "Banorte",
    project: "Mobile Banking",
    status: "active",
    workload: "full-time",
    country: "México",
    countryCode: "MX",
    startDate: "2019-08-01",
    yearsOfExperience: 10,
    englishLevel: "C2",
    usClientExperience: true,
    skills: [
      { id: "1", name: "React", yearsOfExperience: 6, level: "expert", verified: true },
      { id: "2", name: "TypeScript", yearsOfExperience: 5, level: "expert", verified: true },
      { id: "3", name: "Next.js", yearsOfExperience: 4, level: "expert", verified: true },
    ],
    certifications: [],
    flags: [],
    trainings: [
      {
        id: "1",
        name: "Management Essentials",
        category: "Leadership",
        status: "completed",
        completedDate: "2023-12-01",
        progress: 100,
      },
    ],
    badges: [{ id: "1", name: "5 Year Club", icon: "⭐", description: "5 años en DaCodes", earnedDate: "2024-08-01" }],
    paymentInfo: {
      scheme: "mixto",
      channel: "BBVA + Deel",
      nextPaymentDate: "2024-02-15",
      estimatedAmount: 75000,
      currency: "MXN",
    },
    vacationDays: 20,
    vacationDaysUsed: 8,
  },
  {
    id: "3",
    fullName: "Ana Sofía Hernández",
    preferredName: "Sofi",
    email: "sofia.hernandez@dacodes.com",
    avatar: "/young-professional-woman-smiling.png",
    role: "UX Designer",
    seniority: "Mid",
    service: "UI/UX Studio",
    client: "Kavak",
    project: "App Redesign",
    status: "active",
    workload: "full-time",
    country: "Colombia",
    countryCode: "CO",
    startDate: "2023-01-10",
    yearsOfExperience: 4,
    englishLevel: "B2",
    usClientExperience: false,
    skills: [
      { id: "1", name: "Figma", yearsOfExperience: 4, level: "expert", verified: true },
      { id: "2", name: "User Research", yearsOfExperience: 3, level: "advanced", verified: false },
      { id: "3", name: "Prototyping", yearsOfExperience: 4, level: "expert", verified: true },
    ],
    certifications: [{ id: "1", name: "Google UX Certificate", issuer: "Google", date: "2022-09-15" }],
    flags: [
      {
        id: "1",
        type: "red",
        title: "Entrega tardía",
        description: "Retrasó entrega de mockups por 3 días sin aviso previo",
        date: "2024-01-08",
        reportedBy: "PM del proyecto",
        resolved: true,
        resolvedDate: "2024-01-15",
      },
    ],
    trainings: [
      { id: "1", name: "Design Systems", category: "Design", status: "pending", dueDate: "2024-02-28", progress: 0 },
    ],
    badges: [],
    paymentInfo: {
      scheme: "deel",
      channel: "Deel",
      nextPaymentDate: "2024-02-01",
      estimatedAmount: 2500,
      currency: "USD",
    },
    vacationDays: 12,
    vacationDaysUsed: 2,
  },
  {
    id: "4",
    fullName: "Roberto Sánchez Mora",
    preferredName: "Beto",
    email: "roberto.sanchez@dacodes.com",
    avatar: "/professional-man-glasses.jpg",
    role: "DevOps Engineer",
    seniority: "Senior",
    service: "Infrastructure",
    status: "active",
    workload: "full-time",
    country: "Argentina",
    countryCode: "AR",
    startDate: "2022-06-01",
    yearsOfExperience: 8,
    englishLevel: "B2",
    usClientExperience: true,
    skills: [
      { id: "1", name: "AWS", yearsOfExperience: 6, level: "expert", verified: true },
      { id: "2", name: "Terraform", yearsOfExperience: 4, level: "advanced", verified: true },
      { id: "3", name: "CI/CD", yearsOfExperience: 5, level: "expert", verified: true },
    ],
    certifications: [{ id: "1", name: "AWS DevOps Professional", issuer: "Amazon", date: "2023-04-20" }],
    flags: [],
    trainings: [],
    badges: [{ id: "1", name: "Cloud Master", icon: "☁️", description: "Experto en cloud", earnedDate: "2023-05-01" }],
    paymentInfo: {
      scheme: "pb",
      channel: "Payoneer",
      nextPaymentDate: "2024-02-05",
      estimatedAmount: 4000,
      currency: "USD",
    },
    vacationDays: 15,
    vacationDaysUsed: 3,
  },
  {
    id: "5",
    fullName: "Fernanda López Castillo",
    preferredName: "Fer",
    email: "fernanda.lopez@dacodes.com",
    avatar: "/professional-woman-short-hair.jpg",
    role: "Frontend Developer",
    seniority: "Junior",
    service: "Core Development",
    squad: "Squad Phoenix",
    client: "Banorte",
    status: "onboarding",
    workload: "full-time",
    country: "México",
    countryCode: "MX",
    startDate: "2024-01-15",
    yearsOfExperience: 2,
    englishLevel: "B1",
    usClientExperience: false,
    skills: [
      { id: "1", name: "React", yearsOfExperience: 2, level: "intermediate", verified: false },
      { id: "2", name: "JavaScript", yearsOfExperience: 2, level: "intermediate", verified: true },
    ],
    certifications: [],
    flags: [],
    trainings: [
      {
        id: "1",
        name: "DaCodes Onboarding",
        category: "Onboarding",
        status: "in-progress",
        dueDate: "2024-02-15",
        progress: 40,
      },
      { id: "2", name: "React Advanced", category: "Technical", status: "pending", dueDate: "2024-03-01", progress: 0 },
    ],
    badges: [],
    paymentInfo: {
      scheme: "nomina",
      channel: "Santander",
      nextPaymentDate: "2024-02-15",
      estimatedAmount: 25000,
      currency: "MXN",
    },
    vacationDays: 10,
    vacationDaysUsed: 0,
  },
]

export const mockVacationRequests: VacationRequest[] = [
  {
    id: "1",
    employeeId: "1",
    startDate: "2024-02-20",
    endDate: "2024-02-25",
    days: 4,
    status: "pending",
    type: "vacation",
    notes: "Viaje familiar planeado",
    createdAt: "2024-01-28",
  },
  {
    id: "2",
    employeeId: "3",
    startDate: "2024-03-01",
    endDate: "2024-03-05",
    days: 3,
    status: "approved",
    type: "vacation",
    approvedBy: "Carlos Mendoza",
    createdAt: "2024-01-20",
  },
]

export const mockNotifications: Notification[] = [
  {
    id: "1",
    title: "Nueva solicitud de vacaciones",
    message: "María García ha solicitado 4 días de vacaciones",
    type: "info",
    read: false,
    createdAt: "2024-01-28T10:30:00",
    link: "/admin/vacations",
  },
  {
    id: "2",
    title: "Documento pendiente de firma",
    message: "Tienes 2 documentos pendientes de firma",
    type: "warning",
    read: false,
    createdAt: "2024-01-27T15:00:00",
    link: "/documents",
  },
  {
    id: "3",
    title: "Training completado",
    message: "Has completado el curso 'AI Fundamentals'",
    type: "success",
    read: true,
    createdAt: "2024-01-20T09:00:00",
  },
]

export const mockDocuments: Document[] = [
  {
    id: "1",
    name: "Contrato Laboral 2024",
    type: "contract",
    category: "legal",
    url: "/documents/contract-2024.pdf",
    uploadedAt: "2024-01-15",
    uploadedBy: "HR System",
    status: "signed",
    signedAt: "2024-01-16",
    requiresSignature: true,
    employeeId: "1",
    size: "245 KB",
    description: "Contrato de trabajo indefinido actualizado para 2024",
  },
  {
    id: "2",
    name: "Política de Home Office",
    type: "policy",
    category: "hr",
    url: "/documents/home-office-policy.pdf",
    uploadedAt: "2024-01-10",
    status: "pending",
    requiresSignature: true,
    size: "128 KB",
    description: "Nueva política de trabajo remoto e híbrido",
  },
  {
    id: "3",
    name: "Recibo de Nómina - Enero 2024",
    type: "payslip",
    category: "finance",
    url: "/documents/payslip-jan-2024.pdf",
    uploadedAt: "2024-01-31",
    status: "signed",
    requiresSignature: false,
    employeeId: "1",
    size: "89 KB",
  },
  {
    id: "4",
    name: "Certificado AWS Solutions Architect",
    type: "certificate",
    category: "training",
    url: "/documents/aws-cert.pdf",
    uploadedAt: "2023-06-15",
    status: "signed",
    requiresSignature: false,
    employeeId: "1",
    size: "156 KB",
    expiresAt: "2026-06-15",
  },
  {
    id: "5",
    name: "NDA - Proyecto Confidencial",
    type: "contract",
    category: "legal",
    url: "/documents/nda-project.pdf",
    uploadedAt: "2024-02-01",
    status: "pending",
    requiresSignature: true,
    size: "67 KB",
    description: "Acuerdo de confidencialidad para nuevo proyecto",
  },
  {
    id: "6",
    name: "Código de Conducta",
    type: "policy",
    category: "hr",
    url: "/documents/code-of-conduct.pdf",
    uploadedAt: "2023-12-01",
    status: "signed",
    signedAt: "2023-12-05",
    requiresSignature: true,
    size: "312 KB",
  },
]

export const mockCourses: Course[] = [
  {
    id: "1",
    title: "AI Fundamentals for Developers",
    description:
      "Aprende los conceptos básicos de inteligencia artificial y machine learning aplicados al desarrollo de software.",
    category: "technical",
    duration: "8 horas",
    level: "intermediate",
    instructor: "Dr. Miguel Ángel Torres",
    thumbnail: "/ai-neural-network-abstract.jpg",
    modules: [
      { id: "1", title: "Introducción a la IA", duration: "45 min", type: "video" },
      { id: "2", title: "Machine Learning Basics", duration: "1.5 hrs", type: "video" },
      { id: "3", title: "Quiz: Conceptos de ML", duration: "20 min", type: "quiz" },
      { id: "4", title: "Redes Neuronales", duration: "2 hrs", type: "video" },
      { id: "5", title: "Práctica: Tu primer modelo", duration: "2 hrs", type: "exercise" },
    ],
    enrolledCount: 156,
    rating: 4.8,
    tags: ["AI", "Machine Learning", "Python"],
    mandatory: false,
    createdAt: "2023-11-15",
  },
  {
    id: "2",
    title: "Leadership 101: De Developer a Tech Lead",
    description: "Desarrolla las habilidades necesarias para liderar equipos técnicos de manera efectiva.",
    category: "leadership",
    duration: "12 horas",
    level: "advanced",
    instructor: "Carolina Vega",
    thumbnail: "/leadership-team-collaboration.jpg",
    modules: [
      { id: "1", title: "El rol del Tech Lead", duration: "1 hr", type: "video" },
      { id: "2", title: "Comunicación efectiva", duration: "2 hrs", type: "video" },
      { id: "3", title: "Gestión de conflictos", duration: "1.5 hrs", type: "video" },
      { id: "4", title: "One-on-ones efectivos", duration: "1 hr", type: "reading" },
      { id: "5", title: "Quiz: Situaciones de liderazgo", duration: "30 min", type: "quiz" },
    ],
    enrolledCount: 89,
    rating: 4.9,
    tags: ["Leadership", "Management", "Soft Skills"],
    mandatory: false,
    createdAt: "2023-10-01",
  },
  {
    id: "3",
    title: "DaCodes Onboarding",
    description: "Conoce la cultura, procesos y herramientas de DaCodes. Obligatorio para todos los nuevos ingresos.",
    category: "onboarding",
    duration: "4 horas",
    level: "beginner",
    instructor: "People Team",
    thumbnail: "/welcome-onboarding-office.jpg",
    modules: [
      { id: "1", title: "Bienvenida a DaCodes", duration: "30 min", type: "video" },
      { id: "2", title: "Nuestra cultura", duration: "45 min", type: "video" },
      { id: "3", title: "Herramientas y accesos", duration: "1 hr", type: "reading" },
      { id: "4", title: "Procesos internos", duration: "1 hr", type: "video" },
      { id: "5", title: "Quiz de onboarding", duration: "15 min", type: "quiz" },
    ],
    enrolledCount: 234,
    rating: 4.7,
    tags: ["Onboarding", "Culture", "Processes"],
    mandatory: true,
    createdAt: "2023-01-01",
  },
  {
    id: "4",
    title: "React & Next.js Avanzado",
    description: "Domina patrones avanzados de React, Server Components, y las últimas features de Next.js.",
    category: "technical",
    duration: "16 horas",
    level: "advanced",
    instructor: "Carlos Mendoza",
    thumbnail: "/react-nextjs-code-programming.jpg",
    modules: [
      { id: "1", title: "React Server Components", duration: "2 hrs", type: "video" },
      { id: "2", title: "App Router Deep Dive", duration: "2.5 hrs", type: "video" },
      { id: "3", title: "Data Fetching Patterns", duration: "2 hrs", type: "video" },
      { id: "4", title: "Proyecto: Full-stack App", duration: "6 hrs", type: "exercise" },
    ],
    enrolledCount: 178,
    rating: 4.9,
    tags: ["React", "Next.js", "TypeScript"],
    mandatory: false,
    createdAt: "2024-01-05",
  },
  {
    id: "5",
    title: "Seguridad Informática para Developers",
    description: "Aprende las mejores prácticas de seguridad en el desarrollo de aplicaciones web.",
    category: "compliance",
    duration: "6 horas",
    level: "intermediate",
    instructor: "Roberto Sánchez",
    thumbnail: "/cybersecurity-lock-shield.png",
    modules: [
      { id: "1", title: "OWASP Top 10", duration: "1.5 hrs", type: "video" },
      { id: "2", title: "Autenticación segura", duration: "1.5 hrs", type: "video" },
      { id: "3", title: "SQL Injection & XSS", duration: "1 hr", type: "video" },
      { id: "4", title: "Quiz de seguridad", duration: "30 min", type: "quiz" },
    ],
    enrolledCount: 145,
    rating: 4.6,
    tags: ["Security", "Web Development", "Best Practices"],
    mandatory: true,
    createdAt: "2023-09-01",
  },
  {
    id: "6",
    title: "Design Systems con Figma",
    description: "Crea y mantén sistemas de diseño escalables usando Figma.",
    category: "technical",
    duration: "10 horas",
    level: "intermediate",
    instructor: "Ana Sofía Hernández",
    thumbnail: "/figma-design-system-ui.jpg",
    modules: [
      { id: "1", title: "Fundamentos de Design Systems", duration: "1.5 hrs", type: "video" },
      { id: "2", title: "Componentes en Figma", duration: "2 hrs", type: "video" },
      { id: "3", title: "Variables y estilos", duration: "2 hrs", type: "video" },
      { id: "4", title: "Auto-layout avanzado", duration: "1.5 hrs", type: "video" },
    ],
    enrolledCount: 67,
    rating: 4.8,
    tags: ["Figma", "Design", "UI/UX"],
    mandatory: false,
    createdAt: "2024-01-20",
  },
]

export const mockEnrollments: CourseEnrollment[] = [
  {
    id: "1",
    courseId: "1",
    employeeId: "1",
    progress: 100,
    status: "completed",
    startedAt: "2024-01-05",
    completedAt: "2024-01-20",
    score: 95,
    certificateUrl: "/certificates/ai-fundamentals.pdf",
  },
  {
    id: "2",
    courseId: "2",
    employeeId: "1",
    progress: 60,
    status: "in-progress",
    startedAt: "2024-01-25",
  },
  {
    id: "3",
    courseId: "3",
    employeeId: "5",
    progress: 40,
    status: "in-progress",
    startedAt: "2024-01-15",
  },
  {
    id: "4",
    courseId: "4",
    employeeId: "2",
    progress: 100,
    status: "completed",
    startedAt: "2024-01-10",
    completedAt: "2024-01-28",
    score: 98,
  },
]

export const mockHeadcountData: HeadcountData[] = [
  { month: "Sep", total: 142, active: 138, onboarding: 3, offboarding: 1 },
  { month: "Oct", total: 148, active: 143, onboarding: 4, offboarding: 1 },
  { month: "Nov", total: 152, active: 147, onboarding: 3, offboarding: 2 },
  { month: "Dic", total: 150, active: 146, onboarding: 2, offboarding: 2 },
  { month: "Ene", total: 156, active: 150, onboarding: 5, offboarding: 1 },
  { month: "Feb", total: 162, active: 156, onboarding: 4, offboarding: 2 },
]

export const mockSkillDistribution: SkillDistribution[] = [
  { skill: "React", count: 45, percentage: 28 },
  { skill: "Node.js", count: 38, percentage: 24 },
  { skill: "Python", count: 32, percentage: 20 },
  { skill: "AWS", count: 28, percentage: 18 },
  { skill: "TypeScript", count: 42, percentage: 26 },
  { skill: "Figma", count: 18, percentage: 11 },
  { skill: "Docker", count: 25, percentage: 16 },
  { skill: "PostgreSQL", count: 30, percentage: 19 },
]

export const mockTurnoverData: TurnoverData[] = [
  { month: "Sep", hires: 8, departures: 3, rate: 2.1 },
  { month: "Oct", hires: 10, departures: 4, rate: 2.7 },
  { month: "Nov", hires: 7, departures: 3, rate: 2.0 },
  { month: "Dic", hires: 4, departures: 6, rate: 4.0 },
  { month: "Ene", hires: 12, departures: 2, rate: 1.3 },
  { month: "Feb", hires: 8, departures: 2, rate: 1.2 },
]

export const mockCountryDistribution = [
  { country: "México", code: "MX", count: 98, percentage: 60 },
  { country: "Colombia", code: "CO", count: 28, percentage: 17 },
  { country: "Argentina", code: "AR", count: 18, percentage: 11 },
  { country: "Perú", code: "PE", count: 12, percentage: 8 },
  { country: "Chile", code: "CL", count: 6, percentage: 4 },
]

export const mockSeniorityDistribution = [
  { level: "Junior", count: 35, percentage: 22, color: "#10b981" },
  { level: "Mid", count: 58, percentage: 36, color: "#6366f1" },
  { level: "Senior", count: 48, percentage: 30, color: "#8b5cf6" },
  { level: "Lead", count: 15, percentage: 9, color: "#ec4899" },
  { level: "Principal", count: 6, percentage: 3, color: "#f43f5e" },
]

export const mockHolidays = [
  { date: "2024-02-05", name: "Día de la Constitución" },
  { date: "2024-03-18", name: "Natalicio de Benito Juárez" },
  { date: "2024-05-01", name: "Día del Trabajo" },
  { date: "2024-09-16", name: "Día de la Independencia" },
  { date: "2024-11-18", name: "Revolución Mexicana" },
  { date: "2024-12-25", name: "Navidad" },
]

export const mockEvents = [
  { date: "2024-02-14", name: "DaLove - Día del Amor", type: "event" },
  { date: "2024-02-23", name: "Workshop: AI Tools", type: "training" },
  { date: "2024-03-08", name: "Día Internacional de la Mujer", type: "event" },
  { date: "2024-04-15", name: "Tech Talk: Cloud Architecture", type: "training" },
  { date: "2024-05-10", name: "Team Building", type: "event" },
  { date: "2024-06-20", name: "Hackathon DaCodes", type: "event" },
]
